shared/video-sdk/develop/ensure-channel-quality/reference/web.mdx
Content for "List of audio scenarios" missing.
=> Add missing content for an internal link

shared/video-sdk/develop/_geofencing.mdx, shared/video-sdk/develop/geofencing/project-test/web.mdx
Deleted the extra article title and fixed the numbering.
=> Review geofencing

shared/video-sdk/develop/_audio-and-voice-effects.mdx, shared/video-sdk/develop/audio-and-voice-effects/project-test/ios.mdx
=> Review audio and voice effects

shared/video-sdk/develop/_use-an-extension.mdx
=> Fix section titles

shared/video-sdk/develop/_play-media.mdx, shared/video-sdk/develop/play-media/project-implementation/android.mdx, shared/video-sdk/develop/play-media/project-implementation/ios.mdx, shared/video-sdk/develop/play-media/project-test/android.mdx, shared/video-sdk/develop/play-media/project-test/ios.mdx
Same issue. Need to resolve the conflicting numbered lists under "Test your implementation".
=> Deleted duplicate info for web and fixed sub-titles

shared/common/prerequities.mdx, shared/video-sdk/_get-started-sdk.mdx, shared/video-sdk/get-started/get-started-sdk/project-implementation/index.mdx, shared/video-sdk/get-started/get-started-sdk/project-implementation/react-native.mdx, shared/video-sdk/get-started/get-started-sdk/project-setup/index.mdx, shared/video-sdk/get-started/get-started-sdk/project-setup/react-native.mdx, shared/video-sdk/get-started/get-started-sdk/project-test/index.mdx, shared/video-sdk/get-started/get-started-sdk/project-test/react-native.mdx, shared/voice-sdk/get-started/get-started-sdk/project-implementation/index.mdx, shared/voice-sdk/get-started/get-started-sdk/project-implementation/react-native.mdx, shared/voice-sdk/get-started/get-started-sdk/project-setup/index.mdx, shared/voice-sdk/get-started/get-started-sdk/project-setup/react-native.mdx, shared/voice-sdk/get-started/get-started-sdk/project-test/index.mdx, shared/voice-sdk/get-started/get-started-sdk/project-test/react-native.mdx
- Review this doc after building from this branch: http://localhost:3000/video-calling/get-started/get-started-sdk?platform=react-native
=> React native get started VideoCall+ILS+Voice Call

shared/video-sdk/develop/play-media/project-implementation/flutter.mdx, shared/video-sdk/develop/play-media/project-implementation/index.mdx, shared/video-sdk/develop/play-media/project-setup/flutter.mdx, shared/video-sdk/develop/play-media/project-setup/index.mdx, shared/video-sdk/develop/play-media/project-test/flutter.mdx, shared/video-sdk/develop/play-media/project-test/index.mdx, shared/video-sdk/develop/play-media/reference/flutter.mdx, shared/video-sdk/develop/play-media/reference/index.mdx
The local preview for the media player stream does not work when the project is built for Android. The same code works fine when built for Windows. The video plays remotely without any issues in both cases. I suspect this is a bug in the Android implementation.
=> 88 play media files to a channel for flutter

shared/common/prerequities.mdx, shared/video-sdk/get-started/get-started-uikit/project-implementation/index.mdx, shared/video-sdk/get-started/get-started-uikit/project-implementation/react-native.mdx, shared/video-sdk/get-started/get-started-uikit/project-setup/index.mdx, shared/video-sdk/get-started/get-started-uikit/project-setup/react-native.mdx, shared/video-sdk/get-started/get-started-uikit/project-test/index.mdx, shared/video-sdk/get-started/get-started-uikit/project-test/react-native.mdx
Check these docs after building:
- http://localhost:3000/interactive-live-streaming/get-started/get-started-uikit?platform=react-native
- http://localhost:3000/video-calling/get-started/get-started-uikit?platform=react-native
=> UIKit react native docs for Video call and ILS

shared/common/prerequities.mdx, shared/video-sdk/get-started/get-started-uikit/project-implementation/index.mdx, shared/video-sdk/get-started/get-started-uikit/project-implementation/react-native.mdx, shared/video-sdk/get-started/get-started-uikit/project-setup/index.mdx, shared/video-sdk/get-started/get-started-uikit/project-setup/react-native.mdx, shared/video-sdk/get-started/get-started-uikit/project-test/index.mdx, shared/video-sdk/get-started/get-started-uikit/project-test/react-native.mdx
UIKIT for react-native Video call and ILS
=> Uikit react native

shared/video-sdk/integrate-token-generation/project-implementation/index.mdx, shared/video-sdk/integrate-token-generation/project-implementation/react-native.mdx, shared/video-sdk/integrate-token-generation/project-setup/index.mdx, shared/video-sdk/integrate-token-generation/project-setup/react-native.mdx, shared/video-sdk/integrate-token-generation/project-test/index.mdx, shared/video-sdk/integrate-token-generation/project-test/react-native.mdx
- Review these docs in the local build: 
- http://localhost:3000/video-calling/develop/integrate-token-generation?platform=react-native
- http://localhost:3000/voice-calling/develop/integrate-token-generation?platform=react-native
- http://localhost:3000/interactive-live-streaming/develop/integrate-token-generation%20copy?platform=react-native
=> implement token generator

agora-chat/get-started/get-started-uikit.mdx, interactive-live-streaming/get-started/get-started-uikit.mdx, shared/variables/global.js, shared/video-sdk/develop/custom-video-and-audio/project-implementation/ios.mdx, shared/video-sdk/develop/live-streaming-over-multiple-channels/project-implementation/ios.mdx, shared/video-sdk/develop/product-workflow/project-implementation/ios.mdx, shared/video-sdk/get-started/get-started-sdk/project-implementation/ios.mdx, shared/voice-sdk/develop/custom-audio/project-implementation/ios.mdx, shared/voice-sdk/develop/ensure-channel-quality/project-implementation/ios.mdx, shared/voice-sdk/get-started/get-started-sdk/project-implementation/ios.mdx, video-calling/get-started/get-started-uikit.mdx
UIKit -> UI Kit
Swift formatting (styling fixes)
Swift placeholder fixes (`<#placeholder#>`)
=> more splitting UI Kit

shared/variables/global.js, shared/video-sdk/develop/cloud-proxy/project-implementation/index.mdx, shared/video-sdk/develop/cloud-proxy/project-implementation/react-native.mdx, shared/video-sdk/develop/cloud-proxy/project-setup/index.mdx, shared/video-sdk/develop/cloud-proxy/project-setup/react-native.mdx, shared/video-sdk/develop/cloud-proxy/project-test/index.mdx, shared/video-sdk/develop/cloud-proxy/project-test/react-native.mdx, shared/video-sdk/develop/cloud-proxy/reference/index.mdx, shared/video-sdk/develop/cloud-proxy/reference/react-native.mdx
Test these docs:
- http://localhost:3000/video-calling/develop/cloud-proxy?platform=react-native
- http://localhost:3000/voice-calling/develop/cloud-proxy?platform=react-native
- http://localhost:3000/interactive-live-streaming/develop/cloud-proxy?platform=react-native
=> Implement cloud proxy docs for RN

shared/video-sdk/get-started/get-started-sdk/project-implementation/react-native.mdx, shared/video-sdk/get-started/get-started-sdk/project-setup/react-native.mdx, shared/video-sdk/get-started/get-started-sdk/project-test/react-native.mdx, shared/video-sdk/get-started/get-started-sdk/reference/index.mdx, shared/video-sdk/get-started/get-started-sdk/reference/react-native.mdx, shared/voice-sdk/get-started/get-started-sdk/project-implementation/react-native.mdx, shared/voice-sdk/get-started/get-started-sdk/project-setup/react-native.mdx, shared/voice-sdk/get-started/get-started-sdk/project-test/react-native.mdx
Review this doc after building from this branch:
- http://localhost:3000/video-calling/get-started/get-started-sdk?platform=react-native
- http://localhost:3000/voice-calling/get-started/get-started-sdk?platform=react-native
- http://localhost:3000/interactive-live-streaming/get-started/get-started-sdk?platform=react-native
I have validated the code for all 3 products on android.
=> Replace get started project

shared/video-sdk/get-started/get-started-uikit/project-implementation/index.mdx, shared/video-sdk/get-started/get-started-uikit/project-implementation/react-native.mdx, shared/video-sdk/get-started/get-started-uikit/project-setup/index.mdx, shared/video-sdk/get-started/get-started-uikit/project-setup/react-native.mdx, shared/video-sdk/get-started/get-started-uikit/project-test/index.mdx, shared/video-sdk/get-started/get-started-uikit/project-test/react-native.mdx
- Adds RN-Uikit docs back as they were lost in the merge commits.
=> add react-native uikit back

assets/code/video-sdk/get-started-sdk/swift/create-ui.mdx, assets/code/voice-sdk/get-started-sdk/swift/create-ui.mdx, assets/code/voice-sdk/product-workflow/swift/configure-buttons.mdx, shared/video-sdk/get-started/get-started-sdk/project-implementation/swift.mdx
- Swift styling fixes
- Removing more old `.of(` code
=> Edits missing from #337

shared/video-sdk/develop/encrypt-media-streams/project-implementation/index.mdx, shared/video-sdk/develop/encrypt-media-streams/project-implementation/react-native.mdx, shared/video-sdk/develop/encrypt-media-streams/project-setup/react-native.mdx, shared/video-sdk/develop/encrypt-media-streams/project-test/index.mdx, shared/video-sdk/develop/encrypt-media-streams/project-test/react-native.mdx, shared/video-sdk/develop/encrypt-media-streams/reference/index.mdx, shared/video-sdk/develop/encrypt-media-streams/reference/react-native.mdx
- Reference PR: https://github.com/AgoraIO/Docs-Source/pull/292/
=> channel encryption for RN

shared/video-sdk/develop/ensure-channel-quality/project-implementation/index.mdx, shared/video-sdk/develop/ensure-channel-quality/project-implementation/react-native.mdx, shared/video-sdk/develop/ensure-channel-quality/project-setup/index.mdx, shared/video-sdk/develop/ensure-channel-quality/project-setup/react-native.mdx, shared/video-sdk/develop/ensure-channel-quality/project-test/index.mdx, shared/video-sdk/develop/ensure-channel-quality/project-test/react-native.mdx, shared/video-sdk/develop/ensure-channel-quality/reference/index.mdx, shared/video-sdk/develop/ensure-channel-quality/reference/react-native.mdx, shared/voice-sdk/develop/ensure-channel-quality/project-implementation/index.mdx, shared/voice-sdk/develop/ensure-channel-quality/project-implementation/react-native.mdx, shared/voice-sdk/develop/ensure-channel-quality/project-setup/index.mdx, shared/voice-sdk/develop/ensure-channel-quality/project-setup/react-native.mdx, shared/voice-sdk/develop/ensure-channel-quality/project-test/index.mdx, shared/voice-sdk/develop/ensure-channel-quality/project-test/react-native.mdx, shared/voice-sdk/develop/ensure-channel-quality/reference/index.mdx, shared/voice-sdk/develop/ensure-channel-quality/reference/react-native.mdx
=> Channel quality RN

shared/video-sdk/get-started/get-started-sdk/project-implementation/react-native.mdx, shared/video-sdk/get-started/get-started-sdk/project-setup/react-native.mdx, shared/video-sdk/get-started/get-started-uikit/project-setup/react-native.mdx, shared/voice-sdk/get-started/get-started-sdk/project-implementation/react-native.mdx, shared/voice-sdk/get-started/get-started-sdk/project-setup/react-native.mdx
- Replace react-native-agora-rtc-ng with react-native-agora. Also fix related breaking changes in JoinChannelWithOptions method.
=> Use the latest sdk for RN

shared/video-sdk/get-started/get-started-uikit/project-implementation/android.mdx, shared/video-sdk/get-started/get-started-uikit/project-implementation/flutter.mdx, shared/video-sdk/get-started/get-started-uikit/project-implementation/ios.mdx, shared/video-sdk/get-started/get-started-uikit/project-implementation/react-native.mdx, shared/video-sdk/get-started/get-started-uikit/project-implementation/web.mdx, shared/video-sdk/get-started/get-started-uikit/project-setup/flutter.mdx, shared/video-sdk/get-started/get-started-uikit/project-setup/react-native.mdx
Cleaned up the ScrollyCode docs so copy and paste programming works. Please validate.
=> Clean up Scrollycode implementations.

shared/video-sdk/develop/_ensure-channel-quality.mdx, shared/video-sdk/develop/ensure-channel-quality/project-implementation/web.mdx
=> #441 Added optimization modes

shared/interactive-whiteboard/get-started-uikit/web.mdx, shared/video-sdk/develop/_product-workflow.mdx, shared/video-sdk/develop/product-workflow/project-implementation/web.mdx, shared/video-sdk/develop/product-workflow/project-test/web.mdx, shared/video-sdk/get-started/get-started-sdk/project-implementation/web.mdx
=> 440 4x web manage media devices is missing

cloud-recording/get-started/getstarted.md, on-premise-recording/develop/integrate-token-generation.mdx, shared/common/_core-concepts.mdx, shared/video-sdk/_authentication-workflow.mdx
Kishan , please fix the following links. 
{
"url": "`/en/cloud-recording/overview/reference/manage-agora-account/#get-the-app-certificate'",
"name":       "`Manage app certificates'",
"Parent URL": "https://docs-staging.agora.io/en/cloud-recording/overview/core-concepts/, line 46, col 244",
"Real URL": "https://docs-staging.agora.io/en/cloud-recording/overview/reference/manage-agora-account/#get-the-app-certificate",
"Result": "Error: 404 Not Found" **False Positive (Works)**
}, {
"url": "`/en/cloud-recording/reference/pricing/extensions-marketplace/overview/product-overview/'",
"name":       "`Extensions Marketplace'",
"Parent URL": "https://docs-staging.agora.io/en/cloud-recording/reference/pricing/, line 14, col 29460",
"Real URL": …
=> 492 link fixing kishan

video-calling/reference/cloud-proxy-allowed-ips.mdx
@billy-the-fish I changed only the file header, since I assume changing the actual file name will break links and cause other problems. Let me know if the scope of this fix is larger than I thought and I'll update it.
=> Changed header

.github/workflows/test-site.yml, shared/agora-analytics/_data-insight.mdx
There was only one link to Call Inspector on that page and it's now fixed
=> Fixed link to cal search

agora-chat/overview/product-overview.mdx, interactive-live-streaming/overview/product-overview.mdx, on-premise-recording/reference/glossary.mdx, shared/chat-sdk/develop/_authentication.mdx, shared/chat-sdk/get-started/get-started-uikit/next-steps/android.mdx, shared/chat-sdk/get-started/get-started-uikit/prerequisites/web.mdx, shared/chat-sdk/hide/_token-server-new.mdx, shared/chat-sdk/reference/_access-token-2.mdx, shared/chat-sdk/reference/_security-best-practice.mdx, shared/chat-sdk/restful-api/_restful-overview.mdx, shared/chat-sdk/restful-api/shared/authorization.mdx, shared/video-sdk/develop/migration-guide/android.mdx, shared/video-sdk/develop/migration-guide/flutter.mdx, shared/video-sdk/develop/migration-guide/ios.mdx, shared/video-sdk/develop/migration-guide/macos.mdx, shared/video-sdk/develop/migration-guide/windows.mdx, shared/voice-sdk/migration-guide/macos.mdx, video-calling/overview/product-overview.mdx, voice-calling/overview/product-overview.mdx
=> For https://github.com/AgoraIO/Docs-Source/issues/619.

interactive-live-streaming/overview/product-overview.mdx, shared/extensions-marketplace/_use-an-extension.mdx
@atovpeko  Can you have a quick look at this one please.
=> For https://github.com/AgoraIO/Docs-Source/issues/632

.github/workflows/test-site.yml
Testing outputting the deploy URL from Vercel.
=> Testing deployment URL

shared/video-sdk/develop/product-workflow/project-implementation/web.mdx, shared/video-sdk/develop/product-workflow/reference/flutter.mdx
=> Screen sharing fixes

flexible-classroom/overview/product-overview.mdx, shared/common/_core-concepts.mdx, shared/video-sdk/_get-started-sdk.mdx, shared/video-sdk/_get-started-uikit.mdx, shared/voice-sdk/get-started/_get-started-sdk.mdx
=> 681 add sd rtn to the core concepts page

shared/video-sdk/get-started/get-started-uikit/project-setup/flutter.mdx
=> Flutter UIkit update for iOS

shared/video-sdk/develop/_integrate-token-generation.mdx, shared/video-sdk/develop/integrate-token-generation/project-implementation/java.mdx, shared/video-sdk/develop/integrate-token-generation/project-test/java.mdx
=> 739 token generator in android doesnt work as it says

shared/video-sdk/get-started/get-started-sdk/project-implementation/react-native.mdx, shared/voice-sdk/get-started/get-started-sdk/project-implementation/react-native.mdx
- Closes https://github.com/AgoraIO/Docs-Source/issues/696
=> Refactor getPermissions to be called only for android

shared/video-sdk/develop/_live-streaming-over-multiple-channels.mdx
- Resolves https://github.com/AgoraIO/Docs-Source/issues/724
=> Add info about return code

extensions-marketplace/develop/integrate/faceunity.mdx
- Closes https://github.com/AgoraIO/Docs-Source/issues/683
=> Update faceunity doc

shared/video-sdk/develop/play-media/project-implementation/flutter.mdx
- Resolves https://github.com/AgoraIO/Docs-Source/issues/758
=> Fix flutter implementation steps

cloud-recording/develop/online-play.md
- Resolves https://github.com/AgoraIO/Docs-Source/issues/776
=> Add permission to bucket contents

shared/video-sdk/reference/known-issues/web.mdx
=> Update ios 15.x known issue

shared/video-sdk/develop/_ensure-channel-quality.mdx
=> Add high to low stream mapping in reference

shared/variables/global.js
=> Point server gateway variable to correct link

shared/video-sdk/develop/product-workflow/project-implementation/react-native.mdx, shared/video-sdk/develop/product-workflow/project-test/react-native.mdx, shared/video-sdk/get-started/get-started-sdk/project-implementation/react-native.mdx
- Adds react-native screen sharing documentation with code examples
- Tested on android emulator, works
- Small enhancement to get started guide for react-native
=> React native screen sharing

shared/interactive-whiteboard/get-started-uikit/ios.mdx, shared/interactive-whiteboard/get-started/ios.mdx
Updated Xcode version from 10.10 to 12.0
=> Updated Xcode version number

shared/video-sdk/develop/audio-and-voice-effects/project-implementation/react-native.mdx, shared/video-sdk/develop/live-streaming-over-multiple-channels/project-implementation/react-native.mdx, shared/video-sdk/get-started/get-started-sdk/project-implementation/react-native.mdx, shared/voice-sdk/develop/audio-and-voice-effects/project-implementation/react-native.mdx
- Resolves https://github.com/AgoraIO/Docs-Source/issues/882
=> RN 4.1.0 leavechannelEx

shared/video-sdk/develop/ensure-channel-quality/project-implementation/react-native.mdx
- Resolves https://github.com/AgoraIO/Docs-Source/issues/881
- Resolves https://github.com/AgoraIO/Docs-Source/issues/880
- Resolves #879
=> OnClientRoleChanged and log files

shared/extensions-marketplace/drm-play.mdx, shared/extensions-marketplace/drm-play/project-implementation/index.mdx, shared/extensions-marketplace/drm-play/project-implementation/react-native.mdx, shared/extensions-marketplace/drm-play/project-test/index.mdx, shared/extensions-marketplace/drm-play/project-test/react-native.mdx, shared/extensions-marketplace/drm-play/reference/index.mdx, shared/extensions-marketplace/drm-play/reference/react-native.mdx, shared/video-sdk/develop/spatial-audio/project-implementation/react-native.mdx, shared/video-sdk/develop/spatial-audio/project-test/react-native.mdx
=> Drm play for react native

flexible-classroom/reference/supported-platforms.md
- Resolves https://github.com/AgoraIO/Docs-Source/issues/960
=> Cleanup flexible classroom supported platforms doc

shared/extensions-marketplace/ai-noise-suppression.mdx, shared/extensions-marketplace/ai-noise-suppression/project-implementation/index.mdx, shared/extensions-marketplace/ai-noise-suppression/project-implementation/react-native.mdx, shared/extensions-marketplace/ai-noise-suppression/reference/index.mdx, shared/extensions-marketplace/ai-noise-suppression/reference/react-native.mdx
- Rewrites the AI denoiser doc for react-native
=> AI denoiser for RN

shared/video-sdk/develop/_spatial-audio.mdx, shared/video-sdk/develop/spatial-audio/project-implementation/android.mdx, shared/video-sdk/develop/spatial-audio/project-implementation/flutter.mdx, shared/video-sdk/develop/spatial-audio/project-implementation/index.mdx, shared/video-sdk/develop/spatial-audio/project-setup/flutter.mdx, shared/video-sdk/develop/spatial-audio/project-setup/index.mdx, shared/video-sdk/develop/spatial-audio/project-test/android.mdx, shared/video-sdk/develop/spatial-audio/project-test/flutter.mdx, shared/video-sdk/develop/spatial-audio/project-test/index.mdx, shared/video-sdk/develop/spatial-audio/reference/flutter.mdx, shared/video-sdk/develop/spatial-audio/reference/index.mdx
Flutter implementation and Android update
=> 894 Spatial audio implementation for flutter and Android update

shared/extensions-marketplace/virtual-background.mdx, shared/extensions-marketplace/virtual-background/project-implementation/flutter.mdx, shared/extensions-marketplace/virtual-background/project-implementation/index.mdx, shared/extensions-marketplace/virtual-background/project-setup/flutter.mdx, shared/extensions-marketplace/virtual-background/project-setup/index.mdx, shared/extensions-marketplace/virtual-background/project-test/flutter.mdx, shared/extensions-marketplace/virtual-background/project-test/index.mdx, shared/extensions-marketplace/virtual-background/reference/flutter.mdx, shared/extensions-marketplace/virtual-background/reference/index.mdx
=> 1000 Virtual background for Flutter

shared/variables/global.js
Update base URL for API Reference
=> :zap: update variable name

flexible-classroom/develop/integrate-flexible-classroom.mdx, shared/flexible-classroom/integrate-flexible-classroom/android.mdx, shared/flexible-classroom/integrate-flexible-classroom/electron.mdx, shared/flexible-classroom/integrate-flexible-classroom/ios.mdx, shared/flexible-classroom/integrate-flexible-classroom/web.mdx, shared/variables/global.js
Integrate Flexible Classroom document updates for Android, iOS, Web, and Electron platforms.
=> 1038 Update Integrate Flexible Classroom changes.

flexible-classroom/develop/record-a-class.md
=> Update record a classroom doc

flexible-classroom/develop/customize-ui.mdx, shared/flexible-classroom/customize-ui/android.mdx, shared/flexible-classroom/customize-ui/ios.mdx, shared/flexible-classroom/customize-ui/js.mdx
=> Update custom UI doc for Flexible Classroom

shared/video-sdk/develop/product-workflow/project-implementation/react-native.mdx
- Resolves #976 
- Build example:
=> Screensharing and camera video

shared/video-sdk/develop/product-workflow/project-implementation/electron.mdx, shared/video-sdk/develop/product-workflow/project-test/electron.mdx
=> Electron: Allow screenshare to work with camera video

shared/video-sdk/develop/ensure-channel-quality/project-implementation/android.mdx, shared/video-sdk/develop/ensure-channel-quality/project-implementation/electron.mdx, shared/video-sdk/develop/ensure-channel-quality/project-implementation/flutter.mdx, shared/video-sdk/develop/ensure-channel-quality/project-implementation/react-native.mdx, shared/video-sdk/develop/ensure-channel-quality/project-implementation/swift.mdx, shared/video-sdk/develop/ensure-channel-quality/project-implementation/windows.mdx, shared/video-sdk/get-started/get-started-sdk/project-implementation/flutter.mdx, shared/video-sdk/reference/release-notes/ios.mdx, shared/voice-sdk/develop/ensure-channel-quality/project-implementation/android.mdx, shared/voice-sdk/develop/ensure-channel-quality/project-implementation/electron.mdx, shared/voice-sdk/develop/ensure-channel-quality/project-implementation/flutter.mdx, shared/voice-sdk/develop/ensure-channel-quality/project-implementation/react-native.mdx, shared/voice-sdk/develop/ensure-channel-quality/project-implementation/swift.mdx
=> 876-Flutter code update for the SDK quickstart

shared/video-sdk/develop/product-workflow/project-setup/react-native.mdx
=> Add prerequisite for ios

.github/workflows/test-site.yml
- Adding ref to staging in AgoraIO/Docs checkout
=> add branch to AgoraIO/Docs checkout

shared/voice-sdk/_authentication-workflow.mdx
Resolves https://github.com/AgoraIO/Docs-Source/issues/1033
=> Fix wrong param value

shared/video-sdk/get-started/get-started-sdk/project-implementation/flutter.mdx
=> 1099 flutter Quickstart local preview fix

shared/video-sdk/get-started/get-started-sdk/project-implementation/flutter.mdx
=> Add uid note

flexible-classroom/reference/classroom-api.mdx
=> Update classroom api doc

shared/chat-sdk/client-api/messages/manage-messages/understand/android.mdx, shared/common/security/_security-practice.mdx
Resolves https://github.com/AgoraIO/Docs-Source/issues/1093
=> Fix according to customer feedback

extensions-marketplace/develop/integrate/banuba.mdx, shared/variables/global.js
Found a couple of old references to previous packages.
=> Fix package URLs

shared/chat-sdk/client-api/messages/manage-messages/project-implementation/android.mdx, shared/chat-sdk/client-api/messages/manage-messages/project-implementation/ios.mdx, shared/chat-sdk/client-api/messages/manage-messages/project-implementation/unity.mdx, shared/chat-sdk/client-api/messages/manage-messages/project-implementation/windows.mdx, shared/chat-sdk/client-api/messages/manage-messages/understand/android.mdx, shared/chat-sdk/client-api/messages/manage-messages/understand/ios.mdx
- Resolves additional comments from https://github.com/AgoraIO/Docs-Source/issues/1093
=> Additional changes from Chat SDK v1.0.9

assets/code/video-sdk/get-started-sdk/swift/create-ui.mdx, assets/code/video-sdk/get-started-sdk/swift/join-and-leave.mdx, assets/code/voice-sdk/get-started-sdk/swift/create-ui.mdx, shared/video-sdk/develop/stream-raw-audio-and-video/project-implementation/ios.mdx, shared/video-sdk/develop/stream-raw-audio-and-video/project-implementation/swift.mdx, shared/video-sdk/get-started/get-started-sdk/project-implementation/swift.mdx, shared/voice-sdk/develop/stream-raw-audio/project-implementation/ios.mdx, shared/voice-sdk/develop/stream-raw-audio/project-implementation/macos.mdx, shared/voice-sdk/get-started/get-started-sdk/project-implementation/swift.mdx
- Replacing semaphore usage with async/await
=> Semaphore -> Async

shared/notification-center-service/maintain-user-online-status.mdx
=> 1116 updated NCS events numbers

assets/code/voice-sdk/get-started-sdk/swift/create-ui.mdx
Update login button with didSet - no longer updated through join button clicking.
=> Update Login Button

shared/video-sdk/get-started/get-started-uikit/project-setup/react-native.mdx
Added RTM to the setup instruction for React Native UIKit
=> fix: add rtm dep in react-native uikit

flexible-classroom/develop/record-a-class.mdx, shared/flexible-classroom/integrate-flexible-classroom/ios.mdx, shared/flexible-classroom/quickstart/android.mdx, shared/flexible-classroom/quickstart/electron.mdx, shared/flexible-classroom/quickstart/ios.mdx, shared/flexible-classroom/quickstart/web.mdx
=> 1136 flexible classroom updates on review

shared/common/prerequities.mdx, shared/iot/get-started/_get-started-sdk.mdx, shared/iot/get-started/get-started-sdk/project-setup/linux-c.mdx, shared/variables/platform.js
Changes for IOT get started docs for Linux C
Issue https://github.com/AgoraIO/Docs-Source/issues/1017
=> 1017 LinuxC  create the Android authentication guide for MA

iot/reference/agora-console-rest-api.mdx, iot/reference/billing-policies.mdx, iot/reference/channel-management-rest-api.mdx, iot/reference/cloud-proxy-allowed-ips.mdx, iot/reference/firewall.mdx, iot/reference/glossary.mdx, iot/reference/pricing.mdx, iot/reference/release-notes.mdx, iot/reference/restful-authentication.mdx, iot/reference/security.mdx, shared/iot/develop/_ensure-channel-quality.mdx, shared/iot/develop/_media-stream-encryption.mdx, shared/iot/develop/_multi-channel-streaming.mdx, shared/iot/develop/encrypt-media-streams/project-implementation/linux-c.mdx, shared/iot/develop/encrypt-media-streams/project-setup/android.mdx, shared/iot/develop/encrypt-media-streams/project-setup/linux-c.mdx, shared/iot/develop/encrypt-media-streams/project-test/linux-c.mdx, shared/iot/develop/encrypt-media-streams/reference/linux-c.mdx, shared/iot/get-started/get-started-sdk/project-test/linux-c.mdx, shared/iot/release-notes/android.mdx, shared/iot/release-notes/index.mdx, shared/iot/release-notes/linux-c.mdx, shared/video-sdk/_authentication-workflow.mdx, shared/video-sdk/reference/_release-notes.mdx
Issue:
https://github.com/AgoraIO/Docs-Source/issues/1019
Changes made for IOT media stream encryption guide for LinuxC..
There's one issue I found :
After launching the app with Linux terminal (by compiling the updated code with enabling encryption), if the same channel is  joined by another user (Agora web demo console user, which is Unauthorised one  as it desn't have encryption key and salt to connect with first user), then the compiled app got an warning 
`[WRN] Error 120 is captured. Error msg "audio:decrypt error"`
Which is perfectly fine. But it suddenly  stop , which should not be the case.
```
root@DESKTOP-H5KUOIH:/home/varun_gupta_py/Agora/agora_rtsa_sdk/example/out/x86_64# ./hello_rtsa --app-id "5db9f968c5214f009c7e8954c2ae82b5" --channel-id "encryption_test3" --token …
```
=> 1019 LinuxC create the stream encryption guide for ma

shared/video-sdk/authentication-workflow/project-implementation/linux-c.mdx
Issue : https://github.com/AgoraIO/Docs-Source/issues/1017
Some minor changes for LinuxC IOT secure authentication token
=> minor udates on review

shared/iot/develop/_multi-channel-streaming.mdx, shared/iot/develop/encrypt-media-streams/project-implementation/linux-c.mdx, shared/iot/develop/encrypt-media-streams/project-test/linux-c.mdx, shared/iot/develop/ensure-channel-quality/project-test/linux-c.mdx, shared/iot/develop/multi-channel-streaming/project-implementation/android.mdx, shared/iot/develop/multi-channel-streaming/project-implementation/linux-c.mdx, shared/iot/develop/multi-channel-streaming/project-test/android.mdx, shared/iot/develop/multi-channel-streaming/project-test/linux-c.mdx, shared/iot/develop/multi-channel-streaming/reference/linux-c.mdx, shared/video-sdk/authentication-workflow/project-implementation/linux-c.mdx
Issue:
https://github.com/AgoraIO/Docs-Source/issues/1020
@saudsami : As discussed, please update the image inside "Under the Tech" as per changed order.
=> 1020 LinuxC IOT create the sreaming over multple channels doc

shared/video-sdk/get-started/get-started-sdk/project-implementation/android.mdx
=> 1209 -update-android-quickstart-to-emphasize-uid=0-for-local-user

flexible-classroom/develop/supply-course-materials.md, shared/flexible-classroom/customize-ui/js.mdx, shared/flexible-classroom/integrate-flexible-classroom/web.mdx, shared/flexible-classroom/quickstart/web.mdx
=> 1245, 1161 flexible classroom Updates

shared/video-sdk/get-started/get-started-sdk/reference/web.mdx, shared/video-sdk/get-started/get-started-uikit/reference/web.mdx
=> Fix typo in svelte

flexible-classroom/get-started/enable-flexible-classroom.mdx
=> Add filenamePrefix dynamic setting

shared/agora-analytics/_datadog-integration.mdx
=> Fix support link

shared/flexible-classroom/integrate-flexible-classroom/electron.mdx, shared/flexible-classroom/integrate-flexible-classroom/web.mdx
=> Fix uiMode value

shared/signaling/call-invitation/android.mdx, shared/signaling/call-invitation/ios.mdx, shared/signaling/call-invitation/macos.mdx, shared/signaling/call-invitation/web.mdx, shared/signaling/call-invitation/windows.mdx
=> Remove demo project from call invitation

shared/video-sdk/develop/_real-time-transcription.mdx
Added a note to emphasize int `uid`s
Updated the section on the use of Protobuf and added the `onStreamMessage` callback.
Added back the API reference section.
=> 1300 more rtt review updates

shared/video-sdk/authentication-workflow/project-implementation/cpp.mdx, shared/video-sdk/authentication-workflow/project-implementation/windows.mdx, shared/video-sdk/authentication-workflow/project-test/cpp.mdx, shared/video-sdk/authentication-workflow/project-test/csharp.mdx, shared/video-sdk/authentication-workflow/project-test/windows.mdx, shared/video-sdk/authentication-workflow/reference/cpp.mdx, shared/video-sdk/authentication-workflow/reference/csharp.mdx, shared/video-sdk/authentication-workflow/reference/index.mdx, shared/video-sdk/authentication-workflow/reference/windows.mdx, shared/video-sdk/get-started/get-started-sdk/project-implementation/windows.mdx
#Issue
https://github.com/AgoraIO/Docs-Source/issues/167
=> 167 implement the authentication workflow for video sdk windows cpp

shared/video-sdk/develop/_integrate-token-generation.mdx, shared/video-sdk/develop/integrate-token-generation/project-implementation/cpp.mdx, shared/video-sdk/develop/integrate-token-generation/project-implementation/windows.mdx, shared/video-sdk/develop/integrate-token-generation/project-setup/windows.mdx, shared/video-sdk/develop/integrate-token-generation/project-test/windows.mdx, shared/video-sdk/develop/integrate-token-generation/reference/cpp.mdx, shared/video-sdk/develop/integrate-token-generation/reference/windows.mdx
Issue:
https://github.com/AgoraIO/Docs-Source/issues/169
=> 169 integrate a token generator for video sdk windows cpp

shared/video-sdk/develop/_cloud-proxy.mdx, shared/video-sdk/develop/cloud-proxy/project-implementation/index.mdx, shared/video-sdk/develop/cloud-proxy/project-implementation/windows.mdx, shared/video-sdk/develop/cloud-proxy/project-setup/index.mdx, shared/video-sdk/develop/cloud-proxy/project-test/index.mdx, shared/video-sdk/develop/cloud-proxy/project-test/windows.mdx, shared/video-sdk/develop/cloud-proxy/reference/index.mdx, shared/video-sdk/develop/cloud-proxy/reference/windows.mdx
Issue : 
https://github.com/AgoraIO/Docs-Source/issues/1352
=> 1352 Restricted network connection with Cloud Proxy For Windows CPP

shared/video-sdk/develop/_geofencing.mdx, shared/video-sdk/develop/geofencing/project-implementation/index.mdx, shared/video-sdk/develop/geofencing/project-implementation/windows.mdx, shared/video-sdk/develop/geofencing/project-setup/index.mdx, shared/video-sdk/develop/geofencing/project-test/index.mdx, shared/video-sdk/develop/geofencing/project-test/windows.mdx, shared/video-sdk/develop/geofencing/reference/index.mdx, shared/video-sdk/develop/geofencing/reference/windows.mdx
Issue
https://github.com/AgoraIO/Docs-Source/issues/1364
=> 1364 Netwok Geofencing for Windows Cpp

shared/video-sdk/develop/_custom-video-and-audio.mdx, shared/video-sdk/develop/custom-video-and-audio/project-implementation/index.mdx, shared/video-sdk/develop/custom-video-and-audio/project-implementation/windows.mdx, shared/video-sdk/develop/custom-video-and-audio/project-setup/index.mdx, shared/video-sdk/develop/custom-video-and-audio/project-setup/windows.mdx, shared/video-sdk/develop/custom-video-and-audio/project-test/index.mdx, shared/video-sdk/develop/custom-video-and-audio/project-test/windows.mdx, shared/video-sdk/develop/custom-video-and-audio/reference/index.mdx, shared/video-sdk/develop/custom-video-and-audio/reference/windows.mdx
Issue : 
https://github.com/AgoraIO/Docs-Source/issues/175
=> 175-Implement custom video and audio sources for windows cpp

shared/extensions-marketplace/_use-an-extension.mdx, shared/extensions-marketplace/use-an-extension/project-implementation/windows.mdx, shared/extensions-marketplace/use-an-extension/project-test/windows.mdx, shared/extensions-marketplace/use-an-extension/reference/index.mdx, shared/extensions-marketplace/use-an-extension/reference/windows.mdx
Issue
https://github.com/AgoraIO/Docs-Source/issues/180
=> 180-Integrate an Extension into your app for windows cpp

shared/video-sdk/develop/product-workflow/project-setup/react-native.mdx
=> Update dep in react-native screensharing doc

shared/video-sdk/develop/migration-guide/ios.mdx, shared/video-sdk/develop/migration-guide/macos.mdx, shared/voice-sdk/migration-guide/macos.mdx
Referred: https://github.com/AgoraIO/agora_doc_source/commit/89848d63e4459808d9d1da3a657854e77d7c9bd3
Closes #1416
=> Update migration guide

.github/ISSUE_TEMPLATE/.docs-update-issue.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/docs-update-issue.md, .github/ISSUE_TEMPLATE/milestone-management.md, .github/ISSUE_TEMPLATE/new-issue.yml, .github/ISSUE_TEMPLATE/rewrite-a-document-according-to-the-new-architecture.md
- updated existing issues to show whether they are reserved for internal use.
- disabled blank issues.
- added SDK/Product section to doc update issue template.
=> Issue Template Updates
